{{- include "ffc-helm-library.container-secret" (list . "ffc-payment-integrations.container-secret") -}}
{{- define "ffc-payment-integrations.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  AzureWebJobsStorage: {{ quote .Values.container.azureWebJobsStorage }}
  NotifyApiKey: {{ quote .Values.container.notifyApiKey }}
  PortalClientId: {{ quote .Values.container.portalClientId }}
  PortalTenantId: {{ quote .Values.container.portalTenantId }}
  PortalClientSecret: {{ quote .Values.container.portalClientSecret }}
  FunctionSasToken: {{ quote .Values.container.functionSasToken }}
{{- end -}}
